services:
  jobmanager:
    image: flink:2.0.0-scala_2.12-java17
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    env_file:
     - .env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./flink-table-job/target:/opt/flink/usrlib/
      - ./data:/opt/flink/data/
    networks:
      - public
    extra_hosts:
      - "host.docker.internal:host-gateway"

  taskmanager:
    image: flink:2.0.0-scala_2.12-java17
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 2
    env_file:
     - .env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - ./data:/opt/flink/data/
    networks:
      - public
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  public:
    driver: bridge
